import { FileDetails } from "../../documents/models/document.model";

export interface ContactRequest {
  contactId?: string;
  organizationId: string;
  officeId: number;
  officeAccess: number[];
  contactCode?: string;
  userId?: string | null;
  entityTypeId: number;
  ownerTypeId?: number | null;
  vendorTypeId?: number | null;
  properties: string[];
  companyName?: string | null;
  companyEmail?: string | null;
  displayName?: string |null;
  firstName?: string | null;
  lastName?: string | null;
  address1?: string;
  address2?: string;
  city?: string;
  state?: string;
  zip?: string;
  phone?: string | null;
  email: string;
  rating: number;
  notes?: string;
  isInternational: boolean;
  w9Path?: string | null;
  w9FileDetails?: FileDetails | null;
  insurancePath?: string | null;
  insuranceFileDetails?: FileDetails | null;
  insuranceExpiration?: string | null;
  markup?: number | null;
  revenueSplitOwner?: number | null;
  revenueSplitOffice?: number | null;
  workingCapitalBalance?: number | null;
  linenAndTowelFee?: number | null;
  bankName?: string | null;
  routingNumber?: string | null;
  accountNumber?: string | null;
  addAsUser?: number | null;
  isActive: boolean;
 }

export interface ContactResponse {
  contactId: string;
  organizationId: string;
  officeId: number;
  officeName: string;
  officeAccess?: number[];
  contactCode: string;
  userId?: string | null;
  entityTypeId: number;
  ownerTypeId?: number | null;
  vendorTypeId?: number | null;
  properties: string[];
  companyName?: string | null;
  companyEmail?: string | null;
  displayName?: string |null;
  firstName?: string | null;
  lastName?: string | null;
  fullName?: string | null;
  address1?: string;
  address2?: string;
  city?: string;
  state?: string;
  zip?: string;
  phone?: string | null;
  email: string;
  rating: number;
  notes?: string;
  isInternational: boolean;
  w9Path?: string | null;
  w9FileDetails?: FileDetails | null;
  insurancePath?: string | null;
  insuranceFileDetails?: FileDetails | null;
  insuranceExpiration?: string | null;
  markup?: number | null;
  revenueSplitOwner?: number | null;
  revenueSplitOffice?: number | null;
  workingCapitalBalance?: number | null;
  linenAndTowelFee?: number | null;
  bankName?: string | null;
  routingNumber?: string | null;
  accountNumber?: string | null;
  addAsUser?: number | null;
  isActive: boolean;
}

export interface ContactListDisplay {
  contactId: string;
  contactCode: string;
  officeId: number;
  officeName: string;
  officeAccess?: number[];
  fullName?: string | null;
  contactType: string;
  entityTypeId?: number;
  ownerTypeId?: number | null;
  propertyCodesDisplay?: string;
  companyName?: string | null;
  companyEmail?: string | null;
  phone?: string | null;
  email: string;
  rating: number;
  ratingStars?: string;
  isActive: boolean;
}

