import { Routes } from '@angular/router';
import { RouterToken } from './app.routes.tokens';
import { authRouteGuard } from './guards/auth-guard';
import { canDeactivateGuard } from './guards/can-deactivate-guard';
import { unAuthRouteGuard } from './guards/un-auth-guard';

export { RouterToken, RouterUrl } from './app.routes.tokens';

export const authRoutes: Routes = [
  { path: '', redirectTo: RouterToken.Default, pathMatch: 'full' },
  { path: RouterToken.Dashboard, loadComponent: () => import('./authenticated/dashboards/dashboard-shell/dashboard-shell.component').then(m => m.DashboardShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.DashboardStaff, loadComponent: () => import('./authenticated/dashboards/dashboard-staff/dashboard-staff.component').then(m => m.DashboardStaffComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.DashboardOwner, loadComponent: () => import('./authenticated/dashboards/dashboard-owner/dashboard-owner.component').then(m => m.DashboardOwnerComponent), canActivate: [authRouteGuard] },
  { path: 'rentals', redirectTo: RouterToken.ReservationList, pathMatch: 'full' },
  { path: RouterToken.ContactList, loadComponent: () => import('./authenticated/contacts/contacts-shell/contacts-shell.component').then(m => m.ContactsShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Contacts, loadComponent: () => import('./authenticated/contacts/contacts-shell/contacts-shell.component').then(m => m.ContactsShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Contact, loadComponent: () => import('./authenticated/contacts/contact/contact.component').then(m => m.ContactComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.MaintenanceList, loadComponent: () => import('./authenticated/maintenance/maintenance-shell/maintenance-shell.component').then(m => m.MaintenanceShellComponent), canActivate: [authRouteGuard], canDeactivate: [canDeactivateGuard] },
  { path: RouterToken.TicketList, loadComponent: () => import('./authenticated/tickets/ticket-shell/ticket-shell.component').then(m => m.TicketShellComponent), canActivate: [authRouteGuard], canDeactivate: [canDeactivateGuard] },
  { path: RouterToken.Ticket, loadComponent: () => import('./authenticated/tickets/ticket-shell/ticket-shell.component').then(m => m.TicketShellComponent), canActivate: [authRouteGuard], canDeactivate: [canDeactivateGuard] },
  { path: RouterToken.MaintenanceWorkOrder, loadComponent: () => import('./authenticated/maintenance/work-order/work-order.component').then(m => m.WorkOrderComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.WorkOrderCreate, loadComponent: () => import('./authenticated/maintenance/work-order-create/work-order-create.component').then(m => m.WorkOrderCreateComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Maintenance, loadComponent: () => import('./authenticated/maintenance/maintenance-shell/maintenance-shell.component').then(m => m.MaintenanceShellComponent), canActivate: [authRouteGuard], canDeactivate: [canDeactivateGuard] },
  { path: RouterToken.PropertyList, loadComponent: () => import('./authenticated/properties/property-list/property-list.component').then(m => m.PropertyListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Property, loadComponent: () => import('./authenticated/properties/property-shell/property-shell.component').then(m => m.PropertyShellComponent), canActivate: [authRouteGuard], canDeactivate: [canDeactivateGuard] },
  { path: RouterToken.DocumentList, loadComponent: () => import('./authenticated/documents/documents-shell/documents-shell.component').then(m => m.DocumentsShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.DocumentView, loadComponent: () => import('./authenticated/documents/document-view/document-view.component').then(m => m.DocumentViewComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Document, loadComponent: () => import('./authenticated/documents/document/document.component').then(m => m.DocumentComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.EmailList, loadComponent: () => import('./authenticated/email/emails-shell/emails-shell.component').then(m => m.EmailsShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.AlertList, loadComponent: () => import('./authenticated/email/alert-list/alert-list.component').then(m => m.AlertListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.EmailCreate, loadComponent: () => import('./authenticated/email/email-create/email-create.component').then(m => m.EmailCreateComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Email, loadComponent: () => import('./authenticated/email/email/email.component').then(m => m.EmailComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Alert, loadComponent: () => import('./authenticated/email/alert/alert.component').then(m => m.AlertComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.AccountingList, loadComponent: () => import('./authenticated/accounting/accounting-shell/accounting-shell.component').then(m => m.AccountingShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Accounting, loadComponent: () => import('./authenticated/accounting/accounting-shell/accounting-shell.component').then(m => m.AccountingShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.BillingList, loadComponent: () => import('./authenticated/accounting/billing-shell/billing-shell.component').then(m => m.BillingShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Billing, loadComponent: () => import('./authenticated/accounting/invoices/billing/billing.component').then(m => m.BillingComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.BillingCreate, loadComponent: () => import('./authenticated/accounting/invoices/billing-create/billing-create.component').then(m => m.BillingCreateComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.InvoiceCreate, loadComponent: () => import('./authenticated/accounting/invoices/invoice-create/invoice-create.component').then(m => m.InvoiceCreateComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.CostCodesList, loadComponent: () => import('./authenticated/accounting/setup/cost-codes-list/cost-codes-list.component').then(m => m.CostCodesListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.CostCodes, loadComponent: () => import('./authenticated/accounting/setup/cost-codes/cost-codes.component').then(m => m.CostCodesComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.ReservationList, loadComponent: () => import('./authenticated/reservations/reservation-list/reservation-list.component').then(m => m.ReservationListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Reservation, loadComponent: () => import('./authenticated/reservations/reservation-shell/reservation-shell.component').then(m => m.ReservationShellComponent), canActivate: [authRouteGuard], canDeactivate: [canDeactivateGuard] },
  { path: RouterToken.ReservationBoard, loadComponent: () => import('./authenticated/reservations/reservation-board/reservation-board.component').then(m => m.ReservationBoardComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.ReservationBoardSelection, loadComponent: () => import('./authenticated/properties/property-selection/property-selection.component').then(m => m.PropertySelectionComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.QuoteCreate, loadComponent: () => import('./authenticated/properties/quote-create/quote-create.component').then(m => m.QuoteCreateComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.AgentList, loadComponent: () => import('./authenticated/organizations/agent-list/agent-list.component').then(m => m.AgentListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Agent, loadComponent: () => import('./authenticated/organizations/agent/agent.component').then(m => m.AgentComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.UserList, loadComponent: () => import('./authenticated/users/users-shell/users-shell.component').then(m => m.UsersShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.User, loadComponent: () => import('./authenticated/users/user/user.component').then(m => m.UserComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.OrganizationList, loadComponent: () => import('./authenticated/organizations/organization-list/organization-list.component').then(m => m.OrganizationListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Organization, loadComponent: () => import('./authenticated/organizations/organization/organization.component').then(m => m.OrganizationComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.OrganizationConfiguration, loadComponent: () => import('./authenticated/organizations/configuration/configuration.component').then(m => m.ConfigurationComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.AreaList, loadComponent: () => import('./authenticated/organizations/area-list/area-list.component').then(m => m.AreaListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Area, loadComponent: () => import('./authenticated/organizations/area/area.component').then(m => m.AreaComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.BuildingList, loadComponent: () => import('./authenticated/organizations/building-list/building-list.component').then(m => m.BuildingListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Building, loadComponent: () => import('./authenticated/organizations/building/building.component').then(m => m.BuildingComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.OfficeList, loadComponent: () => import('./authenticated/organizations/office-list/office-list.component').then(m => m.OfficeListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Office, loadComponent: () => import('./authenticated/organizations/office/office.component').then(m => m.OfficeComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.AccountingOfficeList, loadComponent: () => import('./authenticated/organizations/accounting-office-list/accounting-office-list.component').then(m => m.AccountingOfficeListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.AccountingOffice, loadComponent: () => import('./authenticated/organizations/accounting-office/accounting-office.component').then(m => m.AccountingOfficeComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.RegionList, loadComponent: () => import('./authenticated/organizations/region-list/region-list.component').then(m => m.RegionListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Region, loadComponent: () => import('./authenticated/organizations/region/region.component').then(m => m.RegionComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.ColorList, loadComponent: () => import('./authenticated/organizations/color-list/color-list.component').then(m => m.ColorListComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Color, loadComponent: () => import('./authenticated/organizations/color/color.component').then(m => m.ColorComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Leads, loadComponent: () => import('./authenticated/leads/leads-shell/leads-shell.component').then(m => m.LeadsShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.OwnerShell, loadComponent: () => import('./authenticated/owners/owner-shell/owner-shell.component').then(m => m.OwnerShellComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Logs, loadComponent: () => import('./authenticated/logs/logs-shell/logs-shell.component').then(m => m.LogsShellComponent), canActivate: [authRouteGuard] },
  { path: `${RouterToken.OwnerShell}/:token`, loadComponent: () => import('./authenticated/owners/owner-shell/owner-shell.component').then(m => m.OwnerShellComponent), canActivate: [authRouteGuard] },
]

const mobileRoutes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'dashboard', loadComponent: () => import('./authenticated/mobile/mobile-dashboard-page/mobile-dashboard-page.component').then(m => m.MobileDashboardPageComponent) },
  { path: 'home', loadComponent: () => import('./authenticated/mobile/mobile-board-page/mobile-board-page.component').then(m => m.MobileBoardPageComponent) },
  { path: 'leads', redirectTo: 'leads/rentals', pathMatch: 'full' },
  { path: 'leads/:tab', loadComponent: () => import('./authenticated/mobile/mobile-leads-page/mobile-leads-page.component').then(m => m.MobileLeadsPageComponent) },
  { path: 'leads/:tab/:id', loadComponent: () => import('./authenticated/mobile/mobile-leads-page/mobile-leads-page.component').then(m => m.MobileLeadsPageComponent) },
  { path: 'tickets', redirectTo: 'tickets/my-tickets', pathMatch: 'full' },
  { path: 'tickets/:tab', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'tickets/:tab/:id', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'maintenance', redirectTo: 'maintenance/inspection', pathMatch: 'full' },
  { path: 'maintenance/inspection/:id/issues', loadComponent: () => import('./authenticated/mobile/mobile-inspection-issues-page/mobile-inspection-issues-page.component').then(m => m.MobileInspectionIssuesPageComponent) },
  { path: 'maintenance/:tab', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'maintenance/:tab/:id', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'reservations', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'reservations/:id', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'properties', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'properties/:id', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'properties/:id/:tab', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'contacts', redirectTo: 'contacts/tenants', pathMatch: 'full' },
  { path: 'contacts/:tab', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'contacts/:tab/:id', loadComponent: () => import('./authenticated/mobile/mobile-section-page/mobile-section-page.component').then(m => m.MobileSectionPageComponent) },
  { path: 'email/create', loadComponent: () => import('./authenticated/mobile/mobile-email-create-page/mobile-email-create-page.component').then(m => m.MobileEmailCreatePageComponent) },
  { path: 'quote-create', loadComponent: () => import('./authenticated/mobile/mobile-quote-create-page/mobile-quote-create-page.component').then(m => m.MobileQuoteCreatePageComponent) },
];

export const routes: Routes = [
	{ path: '', redirectTo: RouterToken.Login, pathMatch: 'full' },
  { path: RouterToken.Login, loadComponent: () => import('./public/login/login.component').then(m => m.LoginComponent), canActivate: [unAuthRouteGuard] },
  { path: 'listing/:token', loadComponent: () => import('./public/property-listing-public/property-listing-public.component').then(m => m.PropertyListingPublicComponent) },
  { path: 'owners/:token', loadComponent: () => import('./authenticated/owners/owner-shell/owner-shell.component').then(m => m.OwnerShellComponent) },
  { path: RouterToken.UserGuide, loadComponent: () => import('./authenticated/shared/user-guide/help-guide/help-guide-page.component').then(m => m.HelpGuidePageComponent), canActivate: [authRouteGuard] },
  { path: RouterToken.Mobile, loadComponent: () => import('./authenticated/mobile/mobile-layout/mobile-layout.component').then(m => m.MobileLayoutComponent), children: mobileRoutes, canActivate: [authRouteGuard] },
  { path: RouterToken.Auth, loadComponent: () => import('./authenticated/shared/layout/layout/layout.component').then(m => m.LayoutComponent), children: authRoutes, canActivate: [authRouteGuard] },
  { path: '**', loadComponent: () => import('./shared/page-not-found/page-not-found.component').then(m => m.PageNotFoundComponent) },
];
