export interface PropertyRequest {
  propertyId?: string;
  propertyCode: string;
  contactId?: string | null;
  propertyStyle?: number;
  propertyStatus?: number;
  propertyType?: number;
  address1: string;
  address2?: string | null;
  suite?: string | null;
  city: string;
  state: string;
  zip: string;
  neighborhood?: string | null;
  crossStreet?: string | null;
  phone: string;
  contact?: string;
  agentId?: string | null;
  furnished?: boolean;
  bedrooms: number;
  bathrooms: number;
  accomodates?: number;
  squareFeet: number;
  bedSizes?: string;
  gated?: boolean;
  heating?: boolean;
  ac?: boolean;
  sofabeds?: boolean;
  smoking?: boolean;
  petsAllowed?: boolean;
  kitchen?: boolean;
  washerDryer?: boolean;
  trashRemoval?: string;
  trashPickupId?: number;
  oven?: boolean;
  refrigerator?: boolean;
  microwave?: boolean;
  dishwasher?: boolean;
  tv?: boolean;
  cable?: boolean;
  dvd?: boolean;
  fastInternet?: boolean;
  minStay?: number;
  maxStay?: number;
  checkInTime?: string;
  checkOutTime?: string;
  availableFrom?: string;
  availableUntil?: string;
  view?: string;
  deck?: boolean;
  garden?: boolean;
  patio?: boolean;
  yard?: boolean;
  commonPool?: boolean;
  privatePool?: boolean;
  jacuzzi?: boolean;
  sauna?: boolean;
  bathtub?: boolean;
  gym?: boolean;
  security?: boolean;
  elevator?: boolean;
  remoteAccess?: boolean;
  assignedParking?: boolean;
  notes?: string;
  amenities?: string;
  alarm?: boolean;
  alarmCode?: string;
  keyCode?: string;
  mailbox?: string;
  amount?: number;
  amountTypeId?: number;
  dailyRate?: number | null;
  monthlyRate?: number | null;
  isActive: boolean;
}

export interface PropertyResponse {
  propertyId: string;
  propertyCode: string;
  contactId?: string | null;
  propertyStyle?: number;
  propertyStatus?: number;
  propertyType?: number;
  address1: string;
  address2: string;
  suite?: string | null;
  city: string;
  state: string;
  zip: string;
  neighborhood?: string | null;
  crossStreet?: string | null;
  phone: string;
  contact: string;
  agentId?: string | null;
  furnished: boolean;
  bedrooms: number;
  bathrooms: number;
  accomodates: number;
  squareFeet: number;
  bedSizes: string;
  gated: boolean;
  heating: boolean;
  ac: boolean;
  sofabeds: boolean;
  smoking: boolean;
  petsAllowed: boolean;
  kitchen: boolean;
  washerDryer: boolean;
  trashRemoval: string;
  trashPickupId: number;
  oven: boolean;
  refrigerator: boolean;
  microwave: boolean;
  dishwasher: boolean;
  tv: boolean;
  cable: boolean;
  dvd: boolean;
  fastInternet: boolean;
  minStay?: number;
  maxStay?: number;
  checkInTime?: string;
  checkOutTime?: string;
  availableFrom?: string;
  availableUntil?: string;
  view: string;
  deck: boolean;
  garden: boolean;
  patio: boolean;
  yard: boolean;
  commonPool: boolean;
  privatePool: boolean;
  jacuzzi: boolean;
  sauna: boolean;
  bathtub: boolean;
  gym: boolean;
  security: boolean;
  elevator: boolean;
  remoteAccess: boolean;
  assignedParking: boolean;
  notes?: string;
  amenities: string;
  alarm: boolean;
  alarmCode: string;
  keyCode: string;
  mailbox: string;
  amount: number;
  amountTypeId: number;
  dailyRate?: number | null;
  monthlyRate?: number | null;
  isActive: boolean;
}

export interface PropertyListDisplay {
  propertyId: string;
  propertyCode: string;
  name: string;
  owner: string;
  contactId: string;
  phone: string;
  bedrooms: number;
  bathrooms: number;
  squareFeet: number;
  isActive: boolean;
}

