import { OwnerStatementActivityLinkSelection, OwnerStatementAmountDrillDownSelection, OwnerStatementDescriptionSegment, OwnerStatementDrillDownMetric, OwnerStatementJournalEntryLineResponse, OwnerStatementJournalEntryLineSearchRequest, OwnerStatementJournalEntryLineSelection, OwnerStatementListViewState, OwnerStatementOfficeGroup, OwnerStatementPropertyActivityLineDisplay, OwnerStatementPropertyActivityLineResponse, OwnerStatementPropertyActivityLineSearchRequest, OwnerStatementPropertyRow, OwnerStatementReportKind, OwnerStatementResponse, OwnerStatementSearchRequest, OwnerStatementVisibleRow } from './owner-statement.model';

export type OwnerReportSearchRequest = OwnerStatementSearchRequest;
export type OwnerReportResponse = OwnerStatementResponse;
export type OwnerReportPropertyRow = OwnerStatementPropertyRow;
export type OwnerReportOfficeGroup = OwnerStatementOfficeGroup;
export type OwnerReportVisibleRow = OwnerStatementVisibleRow;
export type OwnerReportPropertyActivityLineResponse = OwnerStatementPropertyActivityLineResponse;
export type OwnerReportPropertyActivityLineSearchRequest = OwnerStatementPropertyActivityLineSearchRequest;
export type OwnerReportPropertyActivityLineDisplay = OwnerStatementPropertyActivityLineDisplay;
export type OwnerReportDescriptionSegment = OwnerStatementDescriptionSegment;
export type OwnerReportKind = OwnerStatementReportKind;
export type OwnerReportDrillDownMetric = OwnerStatementDrillDownMetric;
export type OwnerReportActivityLinkSelection = OwnerStatementActivityLinkSelection;
export type OwnerReportAmountDrillDownSelection = OwnerStatementAmountDrillDownSelection;
export type OwnerReportListViewState = OwnerStatementListViewState;
export type OwnerReportJournalEntryLineSearchRequest = OwnerStatementJournalEntryLineSearchRequest;
export type OwnerReportJournalEntryLineResponse = OwnerStatementJournalEntryLineResponse;
export type OwnerReportJournalEntryLineSelection = OwnerStatementJournalEntryLineSelection;
